kind: pipeline
type: docker
name: testbuild

steps:
  - name: test
    image: node
    commands:
      - yarn
      - yarn test
  - name: build
    image: node
    commands:
      - yarn
      - yarn build

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: docker
name: deploy

depends_on:
  - testbuild

trigger:
  status:
    - success

steps:
  - name: upload
    image: plugins/s3
    settings:
      bucket: dillon-drone-app
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: build/**/*
      target: .
