kind: pipeline
type: docker
name: en

steps:
  - name: build
    image: yarnpkg/dev
    commands:
      - yarn build
  - name: upload
    image: plugins/s3
    settings:
      bucket: react_app
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: public/**/*
      target: /target/location

trigger:
  branch:
    - master
  event:
    - push
