kind: pipeline
type: docker
name: en

steps:
  - name: build
    image: node
    commands:
      - ls
      - yarn
      - yarn build
  - name: upload
    image: plugins/s3
    settings:
      bucket: dillon-drone-app
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: build/**/*
      target: /
trigger:
  branch:
    - master
  event:
    - push
